#!/bin/bash

MYSQL_USER=$(cat /run/secrets/mariadb_user)
MYSQL_PASSWORD=$(cat /run/secrets/mariadb_password)
MYSQL_ROOT_PASSWORD=$(cat /run/secrets/mariadb_root_password)

mysql -u root -p"$MYSQL_ROOT_PASSWORD" << EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';

CREATE USER IF NOT EXISTS '${WP_ADMIN_USER}'@'%' IDENTIFIED BY '${WP_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '${WP_ADMIN_USER}'@'%';

FLUSH PRIVILEGES;
EOF